apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  labels:
    app: zk
spec:
  serviceName: zk
  replicas: 1
  selector:
    matchLabels:
      app: zk
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: zk
        image: zookeeper:3.9
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        envFrom:
          - configMapRef:
              name: zk-config
        resources:
          requests:
            cpu: "1m"
            memory: 1.5Gi
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: zk-data
          mountPath: /var/lib/zookeeper
          
  volumeClaimTemplates:
  - metadata:
      name: zk-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: zk-storage
      resources:
        requests:
          storage: 20Gi
