apiVersion: apps/v1
kind: Deployment
metadata:
  name: sizif
  labels:
    app: sizif
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sizif
  template:
    metadata:
      labels:
        app: sizif
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
    spec:
      nodeSelector:
        app: zk
      containers:
      - name: sizif
        image: sidivan/sizif:v3.0
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: sizif-config
          - configMapRef:
              name: cassandra-config
          - secretRef:
              name: b2-creds
        resources:
          limits:
            cpu: "1000m"
            memory: 2.25Gi
          requests:
            cpu: "1000m"
            memory: 2.25Gi
        volumeMounts:
          - name: sizif-logs
            mountPath: /app/log
          - name: certs
            mountPath: /etc/ssl/certs/ca-certificates.crt
        ports:
        - containerPort: 9001
          name: prometheus
      volumes:
      - name: sizif-logs
        hostPath:
          path: /var/log/sizif
      - name: certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
        