apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      nodeSelector:
        app: dwarf
      containers:
      - name: grafana
        image: grafana/grafana:main
        ports:
        - name: grafana
          containerPort: 3000
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
      volumes:
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
  volumeClaimTemplates:
  - metadata:
      namespace: monitoring
      name: grafana-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: grafana-storage
      resources:
        requests:
          storage: 10Gi