kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: grafana-storage
provisioner: rancher.io/local-path
allowedTopologies:
- matchLabelExpressions:
  - key: app
    values:
    - prometheus
    - dwarf
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-ssd