apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nestor-canary
  labels:
    app: nestor
spec:
  serviceName: nestor
  replicas: 1
  selector:
    matchLabels:
      app: nestor
      environment: canary
  template:
    metadata:
      labels:
        app: nestor
        environment: canary
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: nestor-local-storage
        image: mongo:6.0.20
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 27017
          name: mongosh
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "250m"
            memory: 1Gi
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
          initialDelaySeconds: 30
          timeoutSeconds: 15
        volumeMounts:
          - name: nestor-local-data
            mountPath: /mongo_volume
          
      - name: nestor
        image: sidivan/nestor:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: prometheus
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        env:
          - name: SERVICE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: global.repo.hosts
            valueFrom: 
              configMapKeyRef:
                name: cassandra-config
                key: hosts
        envFrom:
          - configMapRef:
              name: nestor-config
        volumeMounts:
          - name: nestor-logs
            mountPath: /app/log
          - name: certs
            mountPath: /etc/ssl/certs/ca-certificates.crt
      volumes:
      - name: nestor-logs
        hostPath:
          path: /var/lib/nestor
      - name: certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
  volumeClaimTemplates:
  - metadata:
      name: nestor-local-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nestor-local-storage-storage
      resources:
        requests:
          storage: 30Gi
