apiVersion: v1
kind: ConfigMap
metadata:
  name: nestor-canary-config
data:
  binance.reconnect.period.m: "720"

  binance.spot.data.type: spot
  binance.spot.client.http.uri.schema: https://
  binance.spot.client.http.uri.host: api.binance.com
  binance.spot.client.http.uri.port: "443"
  binance.spot.client.stream.uri.schema: wss://
  binance.spot.client.stream.uri.host: stream.binance.com
  binance.spot.client.stream.uri.port: "443"
  binance.spot.client.use.all.tickers.stream: "false"
  binance.spot.deltas.num.workers: "5"
  binance.spot.deltas.batch.size: "5000"
  binance.spot.book.ticks.num.workers: "5"
  binance.spot.book.ticks.batch.size: "5000"
  binance.spot.exchange.info.update.period.m: "5"
  binance.spot.snapshots.depth: "5000"

  binance.usd.data.type: usd
  binance.usd.client.http.uri.schema: https://
  binance.usd.client.http.uri.host: fapi.binance.com
  binance.usd.client.http.uri.port: "443"
  binance.usd.client.stream.uri.schema: wss://
  binance.usd.client.stream.uri.host: fstream.binance.com
  binance.usd.client.stream.uri.port: "443"
  binance.usd.client.use.all.tickers.stream: "true"
  binance.usd.deltas.num.workers: "1"
  binance.usd.deltas.batch.size: "5000"
  binance.usd.book.ticks.num.workers: "1"
  binance.usd.book.ticks.batch.size: "5000"
  binance.usd.exchange.info.update.period.m: "5"
  binance.usd.snapshots.depth: "1000"

  binance.coin.data.type: coin
  binance.coin.client.http.uri.schema: https://
  binance.coin.client.http.uri.host: dapi.binance.com
  binance.coin.client.http.uri.port: "443"
  binance.coin.client.stream.uri.schema: wss://
  binance.coin.client.stream.uri.host: dstream.binance.com
  binance.coin.client.stream.uri.port: "443"
  binance.coin.client.use.all.tickers.stream: "true"
  binance.coin.deltas.num.workers: "1"
  binance.coin.deltas.batch.size: "5000"
  binance.coin.book.ticks.num.workers: "1"
  binance.coin.book.ticks.batch.size: "5000"
  binance.coin.exchange.info.update.period.m: "5"
  binance.coin.snapshots.depth: "1000"


  mongo.config.timeout.s: "3"
  mongo.config.database.name: binance_data
  mongo.config.num.connection.retries: "3"
  mongo.config.uri.schema: mongodb://
  mongo.config.uri.host: nestor-mongodb.default.svc.cluster.local
  mongo.config.uri.port: "27017"

  mongo.binance.spot.delta.table: spot_deltas
  mongo.binance.spot.snapshot.table: spot_snapshot
  mongo.binance.spot.exchange.info.table: spot_exchange_info
  mongo.binance.spot.book.ticks.table: spot_book_ticks

  mongo.binance.usd.delta.table: usd_deltas
  mongo.binance.usd.snapshot.table: usd_snapshot
  mongo.binance.usd.exchange.info.table: usd_exchange_info
  mongo.binance.usd.book.ticks.table: usd_book_ticks

  mongo.binance.coin.delta.table: coin_deltas
  mongo.binance.coin.snapshot.table: coin_snapshot
  mongo.binance.coin.exchange.info.table: coin_exchange_info
  mongo.binance.coin.book.ticks.table: coin_book_ticks
