apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nestor-canary
  labels:
    app: nestor
spec:
  serviceName: nestor
  replicas: 1
  selector:
    matchLabels:
      app: nestor
      environment: canary
  template:
    metadata:
      labels:
        app: nestor
        environment: canary
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
    spec:
      nodeSelector:
        app: nestor
        environment: canary
      terminationGracePeriodSeconds: 60
      containers:
      - name: nestor-local-storage
        image: mongo:6.0.20
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 27017
          name: mongosh
        resources:
          # limits:
          #   cpu: "750m"
          #   memory: 1Gi
          requests:
            cpu: "750m"
            memory: 1Gi
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
          initialDelaySeconds: 30
          timeoutSeconds: 15
        volumeMounts:
          - name: nestor-local-data
            mountPath: /mongo_volume
          
      - name: nestor
        image: sidivan/nestor:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: prometheus
        resources:
          # limits:
          #   cpu: "1000m"
          #   memory: 2Gi
          requests:
            cpu: "1000m"
            memory: 2Gi
        env:
          - name: SERVICE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
        envFrom:
          - configMapRef:
              name: nestor-canary-config
          - configMapRef:
              name: cassandra-config
        volumeMounts:
          - name: nestor-logs
            mountPath: /app/log
          - name: certs
            mountPath: /etc/ssl/certs/ca-certificates.crt
      volumes:
      - name: nestor-logs
        hostPath:
          path: /var/log/nestor
      - name: certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
  volumeClaimTemplates:
  - metadata:
      name: nestor-local-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nestor-local-storage-storage
      resources:
        requests:
          storage: 30Gi
