apiVersion: v1
kind: ConfigMap
metadata:
  name: nestor-canary-config
data:
  binance.client.stream.uri.schema: wss://
  binance.client.stream.uri.host: stream.binance.com
  binance.client.stream.uri.port: "9443"
  binance.client.http.uri.schema: https://
  binance.client.http.uri.host: api.binance.com
  binance.client.http.uri.port: "443"
  binance.reconnect.period.m: "720"
  binance.exchange.info.update.period.m: "5"
  local.repo.database: binance_data
  local.repo.delta.table: deltas
  local.repo.snapshot.table: snapshots
  local.repo.exchange.info.table: exchange_info
  local.repo.book.ticks.table: book_ticks
  local.repo.uri.schema: mongodb://
  local.repo.uri.host: localhost
  local.repo.uri.port: "27017"
  local.repo.num.connection.retries: "3"
  local.repo.timeout.s: "3"
  dwarf.uri.schema: http://
  dwarf.uri.host: "185.178.44.208"
  dwarf.uri.port: "8080"
  use.local.storage: true
