apiVersion: v1
kind: Service
metadata:
  labels:
    app: nestor
  name: nestor
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9001'
spec:
  ports:
  - port: 9001
  selector:
    app: nestor