apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestor-japan-deployment
  labels:
    app: nestor-japan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestor-japan
  template:
    metadata:
      labels:
        app: nestor-japan
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
    spec:
      nodeSelector:
        app: nestor-japan
      terminationGracePeriodSeconds: 60
      containers:
      - name: nestor
        image: sidivan/nestor:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
          name: prometheus
        env:
          - name: SERVICE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
        envFrom:
          - configMapRef:
              name: nestor-japan-config
          - configMapRef:
              name: cassandra-config
        volumeMounts:
          - name: nestor-logs
            mountPath: /app/log
          - name: certs
            mountPath: /etc/ssl/certs/ca-certificates.crt
      volumes:
      - name: nestor-logs
        hostPath:
          path: /var/log/nestor
      - name: certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
