apiVersion: v1
kind: Service
metadata:
  name: nestor-nodeport-service
spec:
  type: NodePort
  selector:
    app: nestor
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30001