apiVersion: v1
kind: Service
metadata:
  name: registry-hs
  namespace: kube-system
  labels:
    app: registry
spec:
  ports:
  - port: 5000
    name: server
  clusterIP: None
  selector:
    app: registry