apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500