apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docker-registry
  namespace: kube-system
spec:
  serviceName: registry-hs
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
  volumeClaimTemplates:
  - metadata:
      name: registry-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: registry-storage
      resources:
        requests:
          storage: 15Gi