apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docker-registry
  namespace: kube-system
spec:
  serviceName: registry-hs
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
            - name: certs
              mountPath: "/certs"
              readOnly: true
            - name: auth
              mountPath: "/auth"
              readOnly: true
          env:
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/certs/registry.crt"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/certs/registry.key"
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
      volumes:
        - name: certs
          secret:
            secretName: registry-tls
        - name: auth
          secret:
            secretName: registry-auth
  volumeClaimTemplates:
  - metadata:
      name: registry-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: socrates-storage
      resources:
        requests:
          storage: 15Gi