version: '3.8'

services:
  build:
    image: build:develop
    build:
      context: "../.."
      dockerfile: "deployment/sizif/build.Dockerfile"

  sizif:
    build:
      context: "../.."
      dockerfile: "deployment/sizif/run.Dockerfile"
    user: root
    restart: unless-stopped
    depends_on:
      build:
        condition: service_completed_successfully
    volumes:
      - type: bind
        source: '../../cmd/sizif/sizif.yaml'
        target: '/app/sizif.yaml'
      - '/var/log/sizif:/app/log'
      - '/etc/parquet:/parquet'
      - '/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt'
    stop_grace_period: 20s
