apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nestor-mongodb
spec:
  serviceName: nestor-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: nestor-mongodb
  template:
    metadata:
      labels:
        app: nestor-mongodb
    spec:
      nodeSelector:
        app: nestor
      containers:
      - name: mongodb
        image: sidivan/nestor-mongo:v1.0
        imagePullPolicy: Always
        command:
        - mongod
        - --replSet
        - rs0
        - --bind_ip_all
        ports:
        - containerPort: 27017
          name: mongosh
        resources:
          limits:
            cpu: "1000m"
            memory: 2Gi
          requests:
            cpu: "750m"
            memory: 1Gi
        lifecycle:
          postStart:
            exec:
              command: ['/bin/sh', '-c', '/init.sh']
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
          initialDelaySeconds: 10
          timeoutSeconds: 10
        volumeMounts:
          - name: nestor-mongo-data
            mountPath: /mongo_volume
      volumes:
      - name: config
        configMap:
          name: "mongo-init"
  volumeClaimTemplates:
  - metadata:
      name: nestor-mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: nestor-mongo-storage
      resources:
        requests:
          storage: 30Gi