kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nestor-mongo-storage
provisioner: rancher.io/local-path
allowedTopologies:
- matchLabelExpressions:
  - key: app
    values:
    - nestor
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-standard