apiVersion: v1
kind: Service
metadata:
  name: dwarf-nodeport-service
spec:
  type: NodePort
  selector:
    app: dwarf
  ports:
  - port: 8080
    name: http-api
    targetPort: 8080
    nodePort: 38080