apiVersion: v1
kind: Service
metadata:
  labels:
    app: dwarf
  name: dwarf
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9001'
spec:
  ports:
  - port: 9001
    name: metrics
  - port: 8080
    name: http-api
  selector:
    app: dwarf