apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
data:
  socrates.hosts: "cassandra-0.cassandra.default.svc.cluster.local"
  socrates.binace.keyspace: binance_data
  socrates.binace.delta.table: deltas
  socrates.binace.snapshot.table: snapshots
  socrates.binace.book.ticks.table: book_ticks
  socrates.binace.exchange.info.table: exchange_info