apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
data:
  socrates.hosts: "cassandra-0.cassandra.default.svc.cluster.local,cassandra-1.cassandra.default.svc.cluster.local,cassandra-2.cassandra.default.svc.cluster.local,cassandra-3.cassandra.default.svc.cluster.local"
  socrates.binance.keyspace: binance_data

  socrates.binance.spot.delta.table: deltas
  socrates.binance.spot.delta.key.table: deltas_keys
  socrates.binance.spot.snapshot.table: snapshots
  socrates.binance.spot.snapshot.key.table: snapshots_keys
  socrates.binance.spot.book.ticks.table: book_ticks
  socrates.binance.spot.book.ticks.key.table: book_ticks_keys
  socrates.binance.spot.exchange.info.table: exchange_info

  socrates.binance.usd.delta.table: usd_deltas
  socrates.binance.usd.delta.key.table: usd_deltas_keys
  socrates.binance.usd.snapshot.table: usd_snapshots
  socrates.binance.usd.snapshot.key.table: usd_snapshots_keys
  socrates.binance.usd.book.ticks.table: usd_book_ticks
  socrates.binance.usd.book.ticks.key.table: usd_book_ticks_keys
  socrates.binance.usd.exchange.info.table: usd_exchange_info

  socrates.binance.coin.delta.table: coin_deltas
  socrates.binance.coin.delta.key.table: coin_deltas_keys
  socrates.binance.coin.snapshot.table: coin_snapshots
  socrates.binance.coin.snapshot.key.table: coin_snapshots_keys
  socrates.binance.coin.book.ticks.table: coin_book_ticks
  socrates.binance.coin.book.ticks.key.table: coin_book_ticks_keys
  socrates.binance.coin.exchange.info.table: coin_exchange_info